name: Linters and Formatters

on:
    push: #all branches
    pull_request:
        types:
            - opened

    workflow_dispatch:

jobs:
    scan:
        name: gitleaks
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4

            - name: Run Gitleaks             
              uses: gitleaks/gitleaks-action@v2
              env:
                GITLEAKS_CONFIG: './.gitleaks.toml' #optianal step,  gitleaks/gitleaks-action@v2 has prebuild configuration